<?php $__env->startSection('content'); ?>
    <body>
    <div class="mask" style="background-color: rgba(218,112,214,0.6);">
        <div class="p-5 text-center bg-light">
        <h1 class="mb-3">O naszej szkole</h1>
        <h4 class="mb-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut in urna id erat cursus vestibulum. Donec tincidunt justo elit, ac consectetur est vestibulum sit amet. Sed aliquet id est at ullamcorper. Duis commodo eleifend erat ut fermentum. Duis eget quam ut odio viverra porttitor. Proin imperdiet massa sodales leo hendrerit malesuada. Duis at pretium nisi. Vivamus ultrices mollis augue, non commodo ex auctor in. Aenean consectetur commodo convallis. Duis ultricies, justo ut tempus tincidunt, enim lacus vehicula enim, vel facilisis massa augue at sem. Sed nibh purus, semper eget volutpat sit amet, egestas et dolor. Nulla euismod nec leo at pulvinar. Nulla consequat bibendum vulputate. Nulla facilisi. Maecenas rhoncus, arcu vel fermentum finibus, metus est bibendum nibh, nec consequat ex lectus nec justo.

            Nulla a vehicula tortor. Maecenas iaculis efficitur urna, ut commodo tortor finibus a. Suspendisse in luctus eros. Aenean vitae venenatis est, sit amet cursus elit. Curabitur congue lorem et dictum pellentesque. Nam nec cursus sapien. Fusce viverra molestie mi, quis finibus lectus sagittis nec. Fusce viverra orci velit, sed dictum nulla aliquet id. Nullam ut odio eu ipsum tincidunt volutpat.

            Vestibulum ac felis at ex ornare tincidunt. Ut sapien felis, egestas vitae euismod vitae, egestas venenatis tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur metus dolor, tincidunt eu sagittis a, tempor eu dolor. Fusce ac metus vitae magna hendrerit volutpat vitae sit amet sem. Suspendisse sed nulla quis quam vehicula lobortis. Donec convallis varius augue, eget laoreet sapien fringilla molestie. Fusce at ligula tincidunt, pharetra sem quis, volutpat sem. Cras vitae mi et nisi lobortis blandit. Nulla nec venenatis mauris. Vestibulum tempor eros ac dolor maximus tristique. Proin accumsan, eros at lobortis molestie, tortor ipsum vestibulum ex, at sodales metus nibh id arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae quam ac mi fermentum finibus quis ac arcu. Duis dapibus at dui sed laoreet. Curabitur eros sapien, vestibulum ut venenatis eu, accumsan vel ligula.

            Duis ornare, mi nec pretium euismod, nisi nunc suscipit libero, tristique elementum metus augue quis ante. Ut molestie rhoncus facilisis. Cras fermentum vitae ex eu tincidunt. Ut dapibus dignissim sem, ut luctus odio fermentum id. Fusce id leo ut nulla blandit aliquet. Cras ornare enim odio, at maximus turpis semper ac. Donec in tristique mauris, accumsan rhoncus mauris. Sed auctor nibh vel molestie iaculis. Donec quis rhoncus est. Donec varius sed nulla commodo imperdiet. Mauris diam risus, tincidunt sed sagittis ut, porta non purus. Duis non tincidunt lacus.

            Curabitur ac nulla ipsum. Nam vel risus feugiat, consequat magna sed, faucibus nisi. Morbi id viverra dolor. Nunc mauris lacus, tempor sit amet vulputate quis, laoreet sit amet tortor. Donec ut condimentum ligula. Cras a lacinia dolor, vitae facilisis dolor. Quisque sit amet congue dui, tempus pellentesque neque. Suspendisse vel efficitur ligula, quis tempor nulla. Vestibulum eget metus et tortor eleifend egestas. Nullam viverra viverra venenatis. Maecenas at mauris id nunc egestas fermentum. Fusce eros nunc, auctor sit amet sagittis et, dapibus vitae libero. Aliquam erat volutpat. Proin lectus neque, ultrices in rutrum vitae, imperdiet a lectus. Morbi tristique dapibus nulla, a tempor neque consequat placerat. Nulla tempus et mi ut fermentum.

            Curabitur condimentum hendrerit finibus. Praesent a luctus mauris, in mollis enim. Proin ut neque orci. Suspendisse mattis pharetra dolor ac dapibus. Nullam scelerisque lectus urna, sodales gravida felis hendrerit ac. Phasellus posuere libero vel quam gravida dictum ac eget justo. Phasellus ipsum neque, posuere vitae lorem in, volutpat ornare quam. Suspendisse vitae venenatis lectus, sit amet pharetra urna. Duis maximus eget nunc nec hendrerit. Nunc cursus magna eu ipsum venenatis, non scelerisque magna luctus. Vestibulum id nunc augue. Aliquam egestas efficitur diam, vel finibus lacus posuere eget. Fusce vehicula, metus vel gravida laoreet, felis neque facilisis justo, et congue leo purus eget risus. Sed a nulla eros. Pellentesque sagittis, orci vel rhoncus ullamcorper, mi est fermentum nibh, a pharetra justo sem et nulla.</h4>
        </div>
    </div>
    </body>
<?php $__env->stopSection(); ?>

<style>
</style>

<?php echo $__env->make("template.bylejak", \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\Users\48512\YoGrafik\resources\views/szkolainfo.blade.php ENDPATH**/ ?>